version: '3'

services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workdir
    environment:
      PYTHONPATH: /workdir
    command: sleep infinity