version: '3'

services:
    workspace:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        environment:
            PYTHONPATH: /workdir
        volumes:
            - ..:/workdir
        command: sleep infinity